version: 2.1

orbs:
  python: circleci/python@1.4.0

jobs:
  pytest:
    docker:
      - image: cimg/python:3.10.0
    steps:
      - checkout
      - run:
          name: Install python dependencies
          command: |
            sudo apt update
            sudo apt install libopenmpi-dev -y
            pip install --upgrade pip setuptools wheel
            pip install -r requirements.txt
      - run:
          name: Run tests
      
          command: pytest
  standalone-test:
    machine: true
    steps:
      - checkout
      - run: cd tests/integration/test-standalone && docker-compose up --build --abort-on-container-exit
  cluster-test:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: apt update -y && apt install curl ca-certificates gnupg lsb-release -y
      - run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      - run:  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      - run: apt update -y && DEBIAN_FRONTEND=noninteractive apt-get install docker-ce docker-ce-cli containerd.io -y 
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            mv ~/docker-compose /usr/local/bin/docker-compose

      - run: cd tests/integration/test-cluster && docker-compose up --build --abort-on-container-exit

workflows:
  sample:
    jobs:
      - pytest
      - standalone-test
      - cluster-test