version: 2.1

orbs:
  python: circleci/python@1.4.0

jobs:
  pytest:
    docker:
      - image: cimg/python:3.10.0
    steps:
      - checkout
      - run:
          name: Install python dependencies
          command: |
            sudo apt update
            sudo apt install libopenmpi-dev -y
            pip install --upgrade pip setuptools wheel
            pip install -r requirements.txt
      - run:
          name: Run tests
      
          command: pytest
  standalone-test:
    machine: true
    steps:
      - checkout
      - run: cd tests/integration/test-standalone && docker-compose up --build --abort-on-container-exit
  cluster-test:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: cd tests/integration/test-cluster && docker-compose up --build --abort-on-container-exit

workflows:
  sample:
    jobs:
      - pytest
      - standalone-test
      - cluster-test